export const AUTH_SUCCESS = 'AUTH SUCCESS';
export const AUTH_FAILURE = 'AUTH FAILURE';
export const CANCEL_AUTH_FAILURE = 'CANCEL AUTH FAILURE'
export const AUTH_REQUESTED = 'AUTH REQUESTED'
export const SING_OUT_REQUESTED = 'SIGN OUT REQUESTED'
export const SING_OUT_SUCCESS = 'SIGN OUT SUCCESS'