export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const CANCEL_AUTH_FAILURE = 'CANCEL_AUTH_FAILURE';
export const AUTH_REQUESTED = 'AUTH_REQUESTED';
export const SING_OUT_REQUESTED = 'SIGN_OUT_REQUESTED';
export const SING_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';