export const SET_USER_LOCATION_REQUESTED = 'SET_USER_LOCATION_REQUESTED';
export const SET_USER_LOCATION_SUCCESS = 'SET_USER_LOCATION_SUCCESS';
export const REMOVE_USER_LOCATION_REQUESTED = 'REMOVE_USER_LOCATION_REQUESTED';
export const REMOVE_USER_LOCATION_SUCCESS = 'REMOVE_USER_LOCATION_SUCCESS';

export const SHOW_SUGGESTIONS = 'SHOW_SUGGESTIONS';
export const HIDE_SUGGESTIONS = 'HIDE_SUGGESTIONS';

export const FETCH_SUGGESTIONS_REQUESTED = 'FETCH_SUGGESTIONS_REQUESTED';
export const FETCH_SUGGESTIONS_SUCCESS = 'FETCH_SUGGESTIONS_SUCCESS';