export const ADD_USER_LOCATION_REQUESTED = 'ADD USER LOCATION';
export const ADD_USER_LOCATION_SUCCESS = 'ADD USER LOCATION';
export const REMOVE_USER_LOCATION_REQUESTED = 'REMOVE USER LOCATION';
export const REMOVE_USER_LOCATION_SUCCESS = 'REMOVE USER LOCATION';